# check-readme.yml
name: Check README
on:
  push:
    branches: [main]
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check missing file
        run: |
          if [ ! -f NOT_EXIST.md ]; then
            echo "NOT_EXIST.md not found!"
            exit 1
          fi